### ISSUE TITLE
Make Responsive layout of about Us page for mobile screens

### ISSUE THREAD

**Issue by piug-07** [DSC-JSS-NOIDA/Foss-events2.0#1]

**Comment by Chetax** [comment]
I Can Do This By Using Bootstrap i can do this .Please Assign It to me

**Comment by Adityacodesinpython** [comment]
can I start working on this?

**Comment by Vaani-pathariya** [comment]
Are you still willing to work on this issue @Chetax ??

**Comment by Chetax** [comment]
> Are you still willing to work on this issue @Chetax ??

@Vaani-pathariya  Yes

**Comment by Vaani-pathariya** [comment]
> > Are you still willing to work on this issue @Chetax ??
> 
> @Vaani-pathariya  Yes

Ok , assigning it to you

**Comment by Chetax** [comment]
@Vaani-pathariya Please Review My PR
