### ISSUE TITLE
Add events icons in the cards

### ISSUE THREAD

**Issue by piug-07** [DSC-JSS-NOIDA/Foss-events2.0#11]

**Comment by Chetax** [comment]
what kinds of icon should be added,can you give example please

**Comment by Vaani-pathariya** [comment]
We wish to add logo for each event in their respective event cards. For example , for the event : Outreachy , we want its logo to be displayed as well in its card.

**Comment by Chetax** [comment]
@Vaani-pathariya  can i pick up this issue

**Comment by Vaani-pathariya** [comment]
Yes you can

**Comment by Chetax** [comment]
@Vaani-pathariya Please review My Pr (Lokking for 😊Hacktoberfest-accepted)
