### ISSUE TITLE
Apply Queensides font to the website 

### ISSUE THREAD

**Issue by Vaani-pathariya** [DSC-JSS-NOIDA/Foss-events2.0#27]
Design link : https://www.figma.com/file/1JSMaoKNjNXYHn2ABc2ra3/Foss-events2.0?type=design&node-id=4717%3A1283&mode=design&t=NYnbA7Q4UQvLjTcU-1
<img width="565" alt="image" src="https://github.com/DSC-JSS-NOIDA/Foss-events2.0/assets/94799887/cd77a1d0-fb7d-4d42-8f35-13276a36f468">

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign

**Comment by Vaani-pathariya** [comment]
Assigned @IrfanSalim
