### ISSUE TITLE
Redesign feedback form page 

### ISSUE THREAD

**Issue by Vaani-pathariya** [DSC-JSS-NOIDA/Foss-events2.0#29]

**Comment by Panth1823** [comment]
Hey @Vaani-pathariya i can redesign the feedback page .

**Comment by Vaani-pathariya** [comment]
> Hey @Vaani-pathariya i can redesign the feedback page .

Great ! go ahead. Assigning it to you

**Comment by Panth1823** [comment]
Hey can u provide some more details about how u want the feedback page? That would be very helpful for me

**Comment by Vaani-pathariya** [comment]
@Panth1823 try to make it similar to the theme of the first three tabs

**Comment by MITTALBHAVYA** [comment]
hey i have done some changes ,
