### ISSUE TITLE
Redesign event card 

### ISSUE THREAD

**Issue by Vaani-pathariya** [DSC-JSS-NOIDA/Foss-events2.0#30]
1. Redesign event card.
2. Centre align event card contents with equal padding on both sides.

**Comment by Vaani-pathariya** [comment]
Assigning @Judge-Paul

**Comment by zainbinfurqan** [comment]
@Vaani-pathariya  Can i work on this issue?

**Comment by Vaani-pathariya** [comment]
@Judge-Paul is working on this issue , so you can try out #31 @zainbinfurqan

**Comment by Judge-Paul** [comment]
Hey @Vaani-pathariyam, Sorry it's been so long, I've been busy with alot of other projects right now and I couldn't figure out how to do this. I currently don't know when or if I will be chanced to complete this so you can assign it to someone else

**Comment by zainbinfurqan** [comment]
@Vaani-pathariya Can i do that?

**Comment by Vaani-pathariya** [comment]
Assigning it to @zainbinfurqan

**Comment by zainbinfurqan** [comment]
@Vaani-pathariya  please review this PR https://github.com/DSC-JSS-NOIDA/Foss-events2.0/pull/49 for this issue
