### ISSUE TITLE
Change placement of search icon in event search field 

### ISSUE THREAD

**Issue by Vaani-pathariya** [DSC-JSS-NOIDA/Foss-events2.0#32]
<img width="957" alt="image" src="https://github.com/DSC-JSS-NOIDA/Foss-events2.0/assets/94799887/b695870e-41db-4bdc-af54-82db9a40dfaa">

**Comment by frantic-rabbit** [comment]
Ca you Assign it to me?

**Comment by Vaani-pathariya** [comment]
Assigned @frantic-rabbit
