### ISSUE TITLE
Correct the linking of other tabs from feedback page 

### ISSUE THREAD

**Issue by Vaani-pathariya** [DSC-JSS-NOIDA/Foss-events2.0#33]

**Comment by SanchitMahajan236** [comment]
Can you please elaborate about this issue ?
I want to contribute but I am not able to completely understand what you want to be done.

**Comment by Vaani-pathariya** [comment]
> Can you please elaborate about this issue ? I want to contribute but I am not able to completely understand what you want to be done.

Browse this site : https://fossevents2.netlify.app/
click on feedback tab 
then click on event/contact us page : this shows aboutus page instead of the event/contactus page 
this needs to be changed

**Comment by Shantanu-Tiwari** [comment]
Is this issue being worked on? 
If not I would like to work on it.
