### ISSUE TITLE
[Bug] : the link is not working

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [DSC-JSS-NOIDA/Foss-events2.0#39]
Description
The link provide in the instagram and the messge links button is not working

Screenshot
<img width="39" alt="Screenshot 2023-10-09 142633" src="https://github.com/DSC-JSS-NOIDA/Foss-events2.0/assets/130988755/f9c82ba8-2990-42b6-aea1-661b39776cf2">

The highlights links is not working properly

**Comment by Shantanu-Tiwari** [comment]
I would like to work on this issue. Please assign it to me.
