### ISSUE TITLE
[Bug]: Fetch All Events API is fetching events of other users

### ISSUE THREAD

**Issue by Hawkeye2108** [DSC-JSS-NOIDA/Foss-events2.0#45]
####Description
Fetch All Events API is fetching events of other users.

####What should happen:
Events of user should be fetched.

####What should happen instead:
Events of all users are fetched.

**To Reproduce**
1. Sign up using name, email, password and confirm-password for two users.
2. Login using email and password and user receives token on successful login .
3. Add Events from both users.
4. Test Fetch All Events API by giving token in authorization request header.

**Comment by Hawkeye2108** [comment]
@Vaani-pathariya Please check this issue.

**Comment by Vaani-pathariya** [comment]
@Hawkeye2108 go ahead with the issue

**Comment by Hawkeye2108** [comment]
@Vaani-pathariya I have fixed the issue, please check the pull request.
