### ISSUE TITLE
Fix the event searching by date 

### ISSUE THREAD

**Issue by piug-07** [DSC-JSS-NOIDA/Foss-events2.0#5]

**Comment by saura8668** [comment]
Hey @piug-07 can u please assign me this issue?

**Comment by MITTALBHAVYA** [comment]
any update saura8668

**Comment by saura8668** [comment]
@MITTALBHAVYA please review my pull request (fix search by date #56 ). I have made some changes.

**Comment by saura8668** [comment]
Hey @MITTALBHAVYA currently I'm busy in some other stuffs.

**Comment by MITTALBHAVYA** [comment]
i have done that
so u can check
