### ISSUE TITLE
[FEAT]: Update Submit Form API to store messages in the Database

### ISSUE THREAD

**Issue by Hawkeye2108** [DSC-JSS-NOIDA/Foss-events2.0#51]
Update Submit Form API to store name, email and message in the database.

**Comment by Hawkeye2108** [comment]
@Vaani-pathariya  Please check this issue.

**Comment by Vaani-pathariya** [comment]
@Hawkeye2108 go ahead with the issue

**Comment by Hawkeye2108** [comment]
@Vaani-pathariya I have fixed the issue, please check the pull request.
