### ISSUE TITLE
[Bug]: Delete Event API can delete events of other users 

### ISSUE THREAD

**Issue by Hawkeye2108** [DSC-JSS-NOIDA/Foss-events2.0#55]
####Description
Delete API can delete events of other users.

####What should happen:
Events of other users can be deleted.

####What should happen instead:
Events of other users should not be deleted.

To Reproduce

  1. Sign up using name, email, password and confirm-password for two users.
  2. Login using email and password and user receives token on successful login .
  3. Add Events from both users.
  4. Test Delete Event API by giving token in authorization request header and delete events of other users.

**Comment by Hawkeye2108** [comment]
@Vaani-pathariya Please check this issue.

**Comment by Vaani-pathariya** [comment]
Go ahead @Hawkeye2108

**Comment by Hawkeye2108** [comment]
@Vaani-pathariya I have fixed the issue, please check the pull request.
