### ISSUE TITLE
Create an API for contact Us page

### ISSUE THREAD

**Issue by piug-07** [DSC-JSS-NOIDA/Foss-events2.0#6]

**Comment by isoletslicer** [comment]
Hello there, may I contribute for this issue? I think I want to contribute mostly for BE side.

Thank you,

**Comment by isoletslicer** [comment]
Hey @piug-07 

I can do this task for you kindly assign it to me. I can do mostly backend side if you want to assign me.

Looking forward your response,
Thank you.

**Comment by Rohit-Sharmaa** [comment]
@piug-07 can you explain more about this issue

**Comment by Vaani-pathariya** [comment]
@Rohit-Sharmaa  , you need to create an API that can send data from the Contact us page to the backend whenever the user clicks on Submit button after entering all the fields (Name , Email and Message).

**Comment by Rohit-Sharmaa** [comment]
@Vaani-pathariya  yah sure  i started working on this issue can you assign this issue to me ??
