### ISSUE TITLE
Create an API for deleting any event

### ISSUE THREAD

**Issue by piug-07** [DSC-JSS-NOIDA/Foss-events2.0#9]

**Comment by ani-netizen** [comment]
Hey @piug-07 

I can do this task for you kindly assign it to me

**Comment by Vaani-pathariya** [comment]
Assigning it to you @ani-netizen

**Comment by ani-netizen** [comment]
> Assigning it to you @ani-netizen

Hey @Vaani-pathariya 

Thank you for assigning the task. Can you please share some sample data of events that I can use for testing
Also you want only one API for deleting event by id or more APIs based on different parameters

**Comment by Vaani-pathariya** [comment]
> > Assigning it to you @ani-netizen
> 
> Hey @Vaani-pathariya
> 
> Thank you for assigning the task. Can you please share some sample data of events that I can use for testing Also you want only one API for deleting event by id or more APIs based on different parameters

You can take sample data from file : Frontend/data/events.json in master branch 
As of now , id is the only parameter required

**Comment by Vaani-pathariya** [comment]
> Also should we add nodemon package so that server restarts automatically after changes

You may add it as a dev dependency

**Comment by ani-netizen** [comment]
> > > Assigning it to you @ani-netizen
> > 
> > 
> > Hey @Vaani-pathariya
> > Thank you for assigning the task. Can you please share some sample data of events that I can use for testing Also you want only one API for deleting event by id or more APIs based on different parameters
> 
> You can take sample data from file : Frontend/data/events.json in master branch As of now , id is the only parameter required

Hey @Vaani-pathariya 

There is mismatch in the file you specified and the schema. Is it intentional or actual mismatch

**Comment by Vaani-pathariya** [comment]
id is mssing for each event , that would be added by mongodb automatically

**Comment by ani-netizen** [comment]
> id is mssing for each event , that would be added by mongodb automatically

I'm not talking about id 

Schema: {
    title: {
        type: String,
        default: null
    },
    date: {
        type: Date,
        required: true
    },
    website: {
        type: String,
        required: true
    },
    details: {
        type: String,
        required: true
    }
}


Data: {
    "title": "ACCELERATING DEVELOPMENT AND DEPLOYMENT OF OPEN SOURCE",
    "website": "www.opensourceindia.in",
    "start": "19/10/2023",
    "end": "20/10/2023",
    "organisation": "Open Source India",
    "location": "Offline"
  }



see difference in JSON structure

**Comment by Vaani-pathariya** [comment]
Change the schema structure file according to the data file schema that I gave

**Comment by ani-netizen** [comment]
are all the fields required or some are optional

**Comment by Vaani-pathariya** [comment]
required

**Comment by ani-netizen** [comment]
Hey @Vaani-pathariya 

I have completed the task made the pr #37. Kindly go through it
Thank you
